const { withDangerousMod } = require("@expo/config-plugins");
const path = require("path");
const fs = require("fs");

/**
 * The credentials-provider extension (targets/credentials-provider) needs
 * libsodium's C API for the decrypt-only crypto port in VaultCrypto.swift —
 * see that file's header for why it's a *port*, not a reimplementation
 * (same compiled binary the main app already links via react-native-
 * libsodium, not hand-rolled crypto). That target is pure Swift, not a
 * React Native target, so it can't just depend on the react-native-
 * libsodium pod (that would pull in the RN runtime, which can't run inside
 * an app extension's constrained process anyway) — it needs the
 * Clibsodium.xcframework binary linked directly.
 *
 * @bacons/apple-targets picks up a `pods.rb` file inside a target directory
 * automatically (evaluated inside that target's own `target 'X' do ... end`
 * block in the generated Podfile — see ios/Podfile's "apple-targets-
 * extension-loader" section after running prebuild). This plugin's only
 * job is to (re)generate the local podspec that pods.rb references, since
 * the xcframework's absolute path depends on the current machine's
 * node_modules resolution and needs to be resolved fresh at prebuild time
 * — targets/credentials-provider/pods.rb itself is a static, committed file.
 */
module.exports = function withCredentialsProviderPod(config) {
  return withDangerousMod(config, [
    "ios",
    async (config) => {
      const xcframeworkPath = resolveClibsodiumXcframework();
      const targetDir = path.join(config.modRequest.projectRoot, "targets", "credentials-provider");
      // CocoaPods requires vendored_frameworks to be relative to the
      // podspec's own directory — an absolute path fails `pod install`'s
      // validation ("File patterns must be relative").
      const relativeXcframeworkPath = path.relative(targetDir, xcframeworkPath);
      fs.writeFileSync(
        path.join(targetDir, "ClibsodiumXCFramework.podspec"),
        clibsodiumPodspec(relativeXcframeworkPath),
      );
      return config;
    },
  ]);
};

function resolveClibsodiumXcframework() {
  const pkgPath = require.resolve("react-native-libsodium/package.json");
  const pkgRoot = path.dirname(pkgPath);
  const xcframework = path.join(pkgRoot, "libsodium", "build", "libsodium-apple", "Clibsodium.xcframework");
  if (!fs.existsSync(xcframework)) {
    throw new Error(
      `[withCredentialsProviderPod] Expected react-native-libsodium's Clibsodium.xcframework at ${xcframework} but it doesn't exist. Has the package layout changed?`,
    );
  }
  return xcframework;
}

function clibsodiumPodspec(xcframeworkRelativePath) {
  return `# Generated by plugins/withCredentialsProviderPod.js on every \`expo prebuild\` —
# do not edit by hand, it will be overwritten. Referenced from ./pods.rb.
Pod::Spec.new do |s|
  s.name         = "ClibsodiumXCFramework"
  s.version      = "1.0.0"
  s.summary      = "libsodium, vendored for targets/credentials-provider"
  s.homepage     = "https://libsodium.org"
  s.license      = { :type => "ISC" }
  s.author       = "libsodium"
  s.platform     = :ios, "13.0"
  # Loaded via :path (development-pod mode) in pods.rb, which never fetches
  # \`source\` — this is just satisfying Pod::Spec's schema.
  s.source       = { :path => "." }
  s.vendored_frameworks = ${JSON.stringify(xcframeworkRelativePath)}
end
`;
}
